418664// Phidget 1067 Board Serial Number for RA.
421153// Phidget 1067 Board Serial Number for Declination.
9.000000// Gear ratio for planetary connected to RA-stepper.
1.000000// Gear ratio of non planetary/non worm gear in RA.
288.000000// Number of teeth of the RA-worm.
1.800000// Size of the full step for RA-Stepper in degrees.
9.000000// Gear ratio for planetary connected to Declination-stepper.
1.000000// Gear ratio of non planetary/non worm gear in Declination.
213.000000// Number of teeth of the RA-worm.
1.800000// Size of the full step for Declination-Stepper in degrees.
16.000000// Number of microsteps your drive can do - 16 for the 1067-board.
10000.000000// Acceleration in Microsteps/s^2 for Right Ascension Drive.
10000.000000// Acceleration in Microsteps/s^2 for Declination Drive.
0.300000// Maximum Current in A for RA-Drive.
0.300000// Maximum Current in A for Declination Drive.
5.200000// Pixelsize x for guiding camera.
5.200000// Pixelsize y for guiding camera.
1280// Chip width x for guiding camera.
1024// Chip width y for guiding camera.
1000// Focal length of guidescope.
48.000000// Latitude of observation site.
15.000000// Longitude of observation site.
1.000000// UTC Offset of Observation site.
TSC// Name of observation site.
Auxiliary Drive 1// Name of first auxiliary stepper.
Auxiliary Drive 2// Name of second auxiliary stepper.
500// Standard number of microsteps for first auxiliary drive.
500// Standard number of microsteps for second auxiliary drive.
500// Acceleration for both auxiliary drives.
500// Speed for both auxiliary drives.
16// Denominator for microstepping ratio.
0// auxDrive connected to the focuser of the guider.
7.000000// Pixel diagonal size of the DSLR in micron.
1000// Focal length of the main telescope in mm.
3// Minimum range for dithering of DSLR exposures.
15// Maximum range for dithering of DSLR exposures.
